spring:
  application:
    name: template-service
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/surveyanswers?authSource=admin
      database: surveyanswers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/survey_stat
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
